### ISSUE TITLE
[HELP] No connection options were found in any of configurations file

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#24]
**Describe the bug**
When `npm start`, the following error occurred.

```node
> typex@2.1.3 start /srv/zipline/zipline
> node out/src

9/17/2020 8:29:31 AM info    Zipline: Starting Zipline 2.1.3
(node:19180) UnhandledPromiseRejectionWarning: Error: No connection options were found in any of configurations file.
    at ConnectionOptionsReader.<anonymous> (/srv/zipline/zipline/node_modules/typeorm/connection/ConnectionOptionsReader.js:34:35)
    at step (/srv/zipline/zipline/node_modules/tslib/tslib.js:139:27)
    at Object.next (/srv/zipline/zipline/node_modules/tslib/tslib.js:120:57)
    at fulfilled (/srv/zipline/zipline/node_modules/tslib/tslib.js:110:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

- config.json
```json
{
    "database": {
        "type": "postgres",
        "host": "127.0.0.1",
        "port": 5432,
        "username": "zipline",
        "password": "password",
        "database": "zipline",
        "synchronize": true,
        "logging": false,
        "entities": [
            "out/src/entities/**/*.js"
        ]
    },
    "uploader": {
        "length": 6,
        "temp": "/srv/zipline/tmp",
        "upload": "/srv/zipline/files",
        "route": "/u",
        "blacklistedExt": []
    },
    "shortener": {
        "length": 4,
        "route": "/s"
    },
    "notes": {
        "length": 4,
        "route": "/n"
    },
    "core": {
        "secure": false,
        "log": true,
        "adminPassword": "password",
        "sessionSecret": "secret",
        "saltRounds": "10",
        "userTokenLength": 34,
        "ssl": {
            "key": "./ssl/server.key",
            "cert": "./ssl/server.crt"
        },
        "port": {
            "secure": 8000,
            "unsecure": 8000
        }
    },
    "meta": {
        "favicon": "/public/assets/zipline_small_circle.png",
        "title": "Zipline"
    },
    "discordWebhook": {
        "enabled": false,
        "url": "https://canary.discordapp.com/api/webhooks/??/??",
        "username": "Zipline Logs",
        "avatarURL": "some url"
    }
}
```

Could anyone tell me how to fix this issue?

- OS: Debian 10.5
- Node.js: v14.11.0
- npm: 6.14.8
- Typescript: Version 4.0.2

**To Reproduce**
1. Go to 'zipfile'
2. run `npm install`
3. run `npm install pg --save-dev`
4. run `npm run build`
5. run `npm start`

**Expected behavior**
run successfully.

**Screenshots**
None.

**Additional context**
None.

**Comment by dicedtomatoreal** [comment]
Thanks for pointing this issue out. It has been fixed in the latest commit. https://github.com/ZiplineProject/zipline/commit/ff4d3d81d305947b66b87b42e0b1c11407bb4f65

**Comment by mzch** [comment]
Well, another error happened:
```node
> typex@2.1.3 start /srv/zipline/zipline
> node out/src

9/17/2020 8:55:18 AM info    Zipline: Starting Zipline 2.1.3
(node:20127) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at /srv/zipline/zipline/out/src/index.js:47:111
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mzch** [comment]
I opened a new issue, #25
