### ISSUE TITLE
[HELP] TypeError

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#25]
**Describe the bug**
When `npm start`, the following error occurred.
```node
> typex@2.1.3 start /srv/zipline/zipline
> node out/src

9/17/2020 8:55:18 AM info    Zipline: Starting Zipline 2.1.3
(node:20127) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at /srv/zipline/zipline/out/src/index.js:47:111
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
1. `npm start`

**Expected behavior**
Run successfully.

**Screenshots**
None.

**Desktop (please complete the following information):**
None.

**Additional context**
None.

**Comment by dicedtomatoreal** [comment]
This has been fixed in the latest commit. Thanks for opening an issue!

**Comment by mzch** [comment]
Unfortunately using the latest source this still sits.

**Comment by mzch** [comment]
Another issue happened. I will open a new issue.
