### ISSUE TITLE
[HELP] RepositoryNotFoundError and not created out/src

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#26]
**Describe the bug**
1. When `npm start`, the following error occurred.
```node

> typex@2.1.3 start /srv/zipline/zipline
> node out/src

internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '/srv/zipline/zipline/out/src'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typex@2.1.3 start: `node out/src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typex@2.1.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/zipline/.npm/_logs/2020-09-18T12_21_25_726Z-debug.log
```
Now there is no `out/src` directory.
```sh
$ ls out
controllers  core  entities  index.js  interval.js  middleware  server.js  structures  util.js
```

2. Next, I ran `node out`, then the following error occurred.

```node
9/18/2020 4:06:02 AM info    Zipline: Starting Zipline 2.1.3
(node:28601) UnhandledPromiseRejectionWarning: RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/srv/zipline/zipline/node_modules/typeorm/error/RepositoryNotFoundError.js:11:28)
    at EntityManager.getRepository (/srv/zipline/zipline/node_modules/typeorm/entity-manager/EntityManager.js:660:19)
    at Connection.getRepository (/srv/zipline/zipline/node_modules/typeorm/connection/Connection.js:343:29)
    at /srv/zipline/zipline/out/index.js:40:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:28601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please help me.

**To Reproduce**
1. Run `npm start`
2. Run `node out`

**Expected behavior**
Run successfully.

**Screenshots**
None.

**Desktop (please complete the following information):**
None.

**Additional context**
None.

**Comment by dicedtomatoreal** [comment]
I'm not able to reproduce this bug, can you try cloning the repo into a clean directory and trying the build & run steps again? (on wiki)

**Comment by dicedtomatoreal** [comment]
Make sure you use the example config's database section and to not change anything in the database.entities

**Comment by mzch** [comment]
I cloned the source repository and tried `npm install` and `npm run build` again, but `out/src` isn't created.
My config.json is as below:
```json
{
    "database": {
        "type": "postgres",
        "host": "127.0.0.1",
        "port": 5432,
        "username": "zipline",
        "password": "password",
        "database": "zipline",
        "synchronize": true,
        "logging": false,
        "entities": [
            "out/src/entities/**/*.js"
        ]
    },
    "uploader": {
        "length": 6,
        "temp": "/srv/zipline/tmp",
        "upload": "/srv/zipline/files",
        "route": "/u",
        "blacklistedExt": []
    },
    "shortener": {
        "length": 4,
        "route": "/s"
    },
    "notes": {
        "length": 4,
        "route": "/n"
    },
    "core": {
        "secure": false,
        "log": true,
        "adminPassword": "password",
        "sessionSecret": "secret",
        "saltRounds": "10",
        "userTokenLength": 34,
        "ssl": {
            "key": "./ssl/server.key",
            "cert": "./ssl/server.crt"
        },
        "port": {
            "secure": 8000,
            "unsecure": 8000
        }
    },
    "meta": {
        "favicon": "/public/assets/zipline_small_circle.png",
        "title": "Zipline"
    },
    "discordWebhook": {
        "enabled": false,
        "url": "https://canary.discordapp.com/api/webhooks/??/??",
        "username": "Zipline Logs",
        "avatarURL": "some url"
    }
}
```

And when running `node out`, the same error happened.

As a trial, I changed database.entities from `"out/src/entities/**/*.js"` to `"out/entities/**/*.js"`, then ran `node out`

```
9/18/2020 7:58:17 AM info    Zipline: Starting Zipline 2.1.3
9/18/2020 7:58:17 AM info    Connection: Successfully initialized database type: postgres
9/18/2020 7:58:17 AM err     TypeX.Routes: Could not formulate upload static route
```

**Comment by dicedtomatoreal** [comment]
can you paste the output of tsconfig.json?

**Comment by mzch** [comment]
I haven't changed `tsconfig.json`...
```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "module": "commonjs",
        "target": "esnext",
        "resolveJsonModule": true,
        "outDir": "./out",
        "esModuleInterop": true
    },
    "exclude": [
        "node_modules"
    ],
    "include": [
        "src"
    ]
```

**Comment by mzch** [comment]
Zipline creates `user` table but `user` table is reserved and used by PostgreSQL as system default.
Can you change it from `user` to `users`?

**Comment by dicedtomatoreal** [comment]
Ok, i've narrowed down the problem, it seems to just be the entities... try using this for entities
```json
"entities": [
   "out/entities/**/*.js"
]```
If this doesn't work (it works for me) you can try clearing your database.

**Comment by mzch** [comment]
One more issue:
```
9/18/2020 1:06:35 PM info    Zipline: Starting Zipline 2.1.3
9/18/2020 1:06:35 PM info    Connection: Successfully initialized database type: postgres
9/18/2020 1:06:35 PM err     TypeX.Routes: Could not formulate upload static route
```
I think perhaps my config caused but I can't fix it...

**Comment by dicedtomatoreal** [comment]
@mzch The latest commit should fix this, thanks for point these out 👍

**Comment by mzch** [comment]
Run successfully. Thanks! :)
