### ISSUE TITLE
MissingDriverError

### ISSUE THREAD

**Issue by mzch** [ZiplineProject/zipline#42]
When `npm start`, MissingDriverError occurred.

- `next` branch
- Node.js: `v15.0.1` and `v14.11.0`
- npm: `7.0.3`

```js
> zipline-next@2.0.0 start /srv/zipline/zipline
> NODE_ENV=production node dist


  ______       _ _
 |__  (_)_ __ | (_)_ __   ___
   / /| | '_ \| | | '_ \ / _ \
  / /_| | |_) | | | | | |  __/
 /____|_| .__/|_|_|_| |_|\___|
        |_|

GitHub  : https://github.com/ZiplineProject/zipline
Issues  : https://github.com/ZiplineProject/zipline/issues
Docs    : https://zipline.diced.wtf/
Mode    : production
Verbose : no

[10/25/2020 1:31:23 AM] info: Preparing app...
/srv/zipline/zipline/node_modules/typeorm/error/MissingDriverError.js:10
        var _this = _super.call(this) || this;
                           ^

MissingDriverError: Wrong driver: "undefined" given. Supported drivers are: "cordova", "expo", "mariadb", "mongodb", "mssql", "mysql", "oracle", "postgres", "sqlite", "better-sqlite3", "sqljs", "react-native", "aurora-data-api", "aurora-data-api-pg".
    at new MissingDriverError (/srv/zipline/zipline/node_modules/typeorm/error/MissingDriverError.js:10:28)
    at DriverFactory.create (/srv/zipline/zipline/node_modules/typeorm/driver/DriverFactory.js:67:23)
    at new Connection (/srv/zipline/zipline/node_modules/typeorm/connection/Connection.js:53:59)
    at ConnectionManager.create (/srv/zipline/zipline/node_modules/typeorm/connection/ConnectionManager.js:56:26)
    at /srv/zipline/zipline/node_modules/typeorm/index.js:194:66
    at step (/srv/zipline/zipline/node_modules/tslib/tslib.js:141:27)
    at Object.next (/srv/zipline/zipline/node_modules/tslib/tslib.js:122:57)
    at /srv/zipline/zipline/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/srv/zipline/zipline/node_modules/tslib/tslib.js:111:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zipline-next@2.0.0 start: `NODE_ENV=production node dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zipline-next@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /srv/zipline/.npm/_logs/2020-10-25T08_31_24_040Z-debug.log
```

**Comment by mzch** [comment]
Sorry, wrong Zipline.toml...

**Comment by dicedtomatoreal** [comment]
just a reminder to look here https://zipline.diced.wtf/docs/config/faq
